package domain;
import java.awt.Color;


/**
 * The grass can be generated by the Earth entity with a certain probability.
 * 
 * @author Ivan Andres Bernal Sabogal
 * @author César Santiago Malaver Garnica 
 * @version 26-09-2026
 */
public class Grass implements Entity
{
    private EcoSafari habitat;
    
    public Grass(EcoSafari habitat, int row, int column){
        this.habitat = habitat;
        habitat.set((Entity)this, row, column);
    }
    
    public void tic(){
    
    }
    
    public Color getColor(){
        return new Color(86, 150, 50); // verde pasto
    }
    
    public EcoSafari getHabitat(){
        return habitat;
    }
}